-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 15:25:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola_tecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola_tecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola_tecnica` DEFAULT CHARACTER SET utf8 ;
USE `escola_tecnica` ;

-- -----------------------------------------------------
-- Table `escola_tecnica`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_tecnica`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_tecnica`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_tecnica`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(200) NULL,
  `carga_horaria` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_tecnica`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_tecnica`.`matriculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_matricula` VARCHAR(45) NULL,
  `alunos_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_matriculas_alunos`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `escola_tecnica`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `escola_tecnica`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO alunos (id, nome, email, data_nascimento) VALUES 
(null, 'João Silva', 'joao.silva@email.com', '2000-12-31'),
(NULL, 'Lucas Kretschmar', 'lucas.kret@email.com', '2001-10-14'),
(NULL, 'Dinea bruth', 'dinea@email.com', '1985-10-14'),
(NULL, 'Vitor kruy', 'kruy.vito@email.com', '1991-05-20'),
(NULL, 'Frank pete', 'pete.frank@email.com', '1985-10-01'),
(NULL, 'Hugo silva', 'hugo.s@email.com', '1995-01-17');

INSERT INTO cursos (id, nome_curso, carga_horaria) VALUES 
(null, 'Banco de dados', '220h'),
(null, 'Back end', '220h'),
(null, 'Front end', '220h');

INSERT INTO matriculas (id, alunos_id, cursos_id) VALUES 
(100, '1', '1'),
(null, '2', '1'),
(null, '3', '1'),
(null, '4', '1'),
(null, '5', '1'),
(null, '6', '1'),
(null, '1', '2'),
(null, '2', '3'),
(null, '5', '3'),
(null, '2', '2');
 